version: '1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=DBNAME
    ports:
      - '5432:5432'
  myapp:
    image: ojanherdika/e-commerce:v1
    ports:
      - '8080:8080'
    environment:
      - SECRET=SECRET
      - BASE_URL=URL_BASE
      - db_url=URL_DB
    volumes:
      - './my-project:/app'
    depends_on:
      - postgres
